### ISSUE TITLE
eggvance | virtual input overlay for mobile device

### ISSUE THREAD

**Issue by louisgv** [jsmolka/website#4]
Hi friend,

Love your emulator and the wasm implementation! I wanted to implement a mobile UI with an overlay DOM buttons to send input event to eggvance (i.e for mobile devices). However, after several try with something similar to:

```
Module.canvas.dispatchEvent(new KeyboardEvent("keydown", {
    key: "g",
  }))
```

I'm still unable to send input down to the emulator. I was wondering if you might have a solution to this.

Thanks in advance!

**Comment by louisgv** [comment]
Would it be possible for eggvance to expose a keyUp and keyDown method similar to: https://github.com/michelhe/rustboyadvance-ng/blob/master/platform/rustboyadvance-wasm/app/index.js#L228

**Comment by jsmolka** [comment]
You could add extra functions that edit the [KEYINPUT](https://github.com/jsmolka/eggvance/blob/b7ae1021fbcdd87df2c4a8b447cbbb818f30d24f/eggvance/src/keypad/io.h#L5) register directly. Unfortunately I removed the WASM frontend shortly after 0.3 because I didn't want to maintain it and just did it as a proof of concept.

**Comment by jsmolka** [comment]
You might also try dispatching the event to the whole [document ](https://stackoverflow.com/a/12187302) instead.

**Comment by louisgv** [comment]
> You might also try dispatching the event to the whole [document ](https://stackoverflow.com/a/12187302) instead.

I actually tried that initially, for some reason that didn't work.
